nameOverride: ""
fullnameOverride: ""

global:
  gitProviders:
    - github
    - gitlab
  dnsWildCard: ""

gitServers:
  github:
    gitProvider: github
    host: github.com
    eventListener:
      # -- Enable EventListener
      enabled: true
      # -- EventListener resources
      resources:
        requests:
          memory: "64Mi"
          cpu: "50m"
        limits:
          memory: "128Mi"
          cpu: "500m"
      ingress:
        # -- Enable ingress controller resource
        enabled: true
  gitlab:
    gitProvider: gitlab
    host: gitlab.com
    webhook:
      url: "http://gitlab.example.com"
      skipWebhookSSLVerification: false
    eventListener:
      enabled: true
      # -- EventListener resources
      resources:
        requests:
          memory: "64Mi"
          cpu: "50m"
        limits:
          memory: "128Mi"
          cpu: "500m"
      ingress:
        # -- Enable ingress controller resource
        enabled: true
